# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-09 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
    ]
