# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0004_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='lit.Article'),
            preserve_default=False,
        ),
    ]
