# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-11 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0005_comment_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.FloatField(default=0.0, max_length=5.0),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='user_pictures'),
        ),
    ]
