# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-13 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0007_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='num_articles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
