# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0016_auto_20180318_1724'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('user_comment', models.CharField(max_length=128)),
                ('rating', models.FloatField(max_length=5.0)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.UserProfile')),
            ],
        ),
    ]
