# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0018_auto_20180319_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='snippet_title',
            field=models.CharField(default='', max_length=128),
        ),
    ]
