# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0019_snippet_snippet_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f57a0a2-1e53-4d5f-9475-7c4267518728'), editable=False, primary_key=True, serialize=False),
        ),
    ]
