# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:31
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0020_auto_20180319_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('098203fa-468e-4a09-90ce-e192e79e4c19'), editable=False, primary_key=True, serialize=False),
        ),
    ]
