# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0022_auto_20180319_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('snippet_title', models.CharField(default='', max_length=128)),
                ('page', models.IntegerField()),
                ('passage', models.CharField(max_length=500)),
                ('analysis', models.CharField(max_length=1000)),
                ('id', models.UUIDField(default=uuid.UUID('7ef31b70-5a7a-41b2-8897-223c7d5cc979'), editable=False, primary_key=True, serialize=False)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lit.Article')),
            ],
        ),
    ]
