# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0024_auto_20180322_1344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('07fc7358-45fb-42a6-87af-19973c2b147f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
