# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-26 10:26
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lit', '0025_auto_20180326_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e8eea8be-25f6-4af3-a344-1684b9088caa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
